reload:
  description: Reload all multizone_thermostat entities

#proportional
set_pwm_threshold:
  description: Set a new 'minimal_diff' before change switch
  fields:
    entity_id:
      description: Thermostat entity_id
      example: climate.study
    hvac_mode:
      description: hvac mode
      example: heat or cool
    new_threshold:
      description: minimum difference value of proportional controller
      example: 2

set_preset_mode:
  name: Set preset mode
  description: Set preset mode for climate device
  fields:
    entity:
      domain: climate
    preset_mode:
      name: Preset mode
      description: New value of preset mode
      required: true
      example: "away"
      selector:
        text:

# Describes the format for available PIDThermostat services
# PID
set_pid:
  description: Set a new Kp value
  fields:
    entity_id:
      description: Thermostat entity_id
      example: climate.study
    hvac_mode:
      description: hvac mode
      example: heat or cool
    kp:
      description: kp value of PID controller
      example: 2
    ki:
      description: kp value of PID controller
      example: 2
    kd:
      description: kp value of PID controller
      example: 2
    update:
      description: force values to controller
      example: true (default) or false


set_integral:
  description: Set a new integral value
  fields:
    entity_id:
      description: Thermostat entity_id
      example: climate.study
    hvac_mode:
      description: hvac mode
      example: heat or cool
    integral:
      description: integral value of PID controller
      example: 5

#VALVE_PID
set_goal:
  description: Set a new goal value
  fields:
    entity_id:
      description: Thermostat entity_id
      example: climate.study
    hvac_mode:
      description: hvac mode
      example: heat or cool
    goal:
      description: goal value of valve mode controller
      example: 60

#weather mode
set_ka_kb:
  description: Set a new KA value
  fields:
    entity_id:
      description: Thermostat entity_id
      example: climate.study
    hvac_mode:
      description: hvac mode
      example: heat or cool
    ka:
      description: KA value of weather mode controller
      example: 8
    kb:
      description: KB value of weather mode controller
      example: 9

#filter mode
set_filter_mode:
  description: Set a new filter variable
  fields:
    entity_id:
      description: Thermostat entity_id
      example: climate.study
    mode:
      description: mode of filter (integral)
      example: 5

# controlled by master
satelite_mode:
  description: Set satelite under control of master
  fields:
    entity_id:
      description: Thermostat entity_id
      example: climate.study
    control_mode:
      description: True(under control of master), False(not), None (no change)
      example: True
    pwm_time:
      description: interval time for pwm cycle
      example: 50
    offset:
      description: time offset to delay start in seconds
      example: 18
    pwm_timer:
      description: reference start time
      example: 1161611

detailed_output:
  description: Include detailed output (PID, control output) in attributes
  fields:
    entity_id:
      description: Thermostat entity_id
      example: climate.study
    hvac_mode:
      description: hvac mode
      example: heat or cool
    new_mode:
      description: Include detailed output
      example: True or False

