# MASTER
- platform: multizone_thermostat
  name: master
  unique_id: mz_master
  initial_hvac_mode: "off"
  initial_preset_mode: "none"
  room_area: 142 # sum of all areas
  passive_switch_check: True
  heat:
    # honeywell 2-way 24v valve
    entity_id: switch.main_valve
    passive_switch_duration:
      days: 60
    passive_switch_opening_time:
      minutes: 4
    custom_presets:
      night: 15
      holiday: 5
    master_mode:
      satelites: [living, sl1, bathroom, sl2, sl3, sl4, sl5]
      # operation_mode: "continuous"
      operation_mode: "balanced"
      control_interval:
        minutes: 30
      pwm_duration:
        minutes: 30
      pwm_scale: 100
      pwm_resolution: 50
      # try to achieve for the proportional valves a 
      # max opening to 80% of max
      PID_valve_mode:
        goal: .8
        kp: -0.5
        ki: -0.0003
        kd: 0

  restore_from_old_state: False
  restore_parameters: False
  restore_integral: False


- platform: multizone_thermostat
  name: living
  unique_id: mz_living
  sensor: sensor.temp_wk
  filter_mode: 2
  sensor_out: sensor.openweather_temperature
  room_area: 62
  initial_hvac_mode: "off"
  precision: 0.1
  sensor_stale_duration:
    hours: 12
  passive_switch_check: True
  heat:
    # thermostatic actuator
    entity_id: input_boolean.living
    passive_switch_duration:
      days: 60
    passive_switch_opening_time:
      minutes: 4      
    initial_target_temp: 19
    custom_presets:
      night: 15
      holiday: 5    
    proportional_mode:
      control_interval:
        minutes: 15
      pwm_duration:
        minutes: 30
      pwm_scale: 100
      pwm_resolution: 50
      pwm_threshold: 2
      PID_mode:
        kp: 50
        ki: 0.004
        kd: -150000
        window_open_tempdrop: -3.6
      weather_mode:
        ka: 2
        kb: -15

  restore_from_old_state: True
  restore_parameters: True
  restore_integral: True


- platform: multizone_thermostat
  name: sl1
  unique_id: mz_sl1
  sensor: sensor.temp_sl1
  filter_mode: 2
  sensor_out: sensor.openweather_temperature
  room_area: 20
  initial_hvac_mode: "off"
  precision: 0.1
  sensor_stale_duration:
    hours: 12
  passive_switch_check: True
  heat:
    # thermostatic actuator
    entity_id: switch.verdeler_8
    passive_switch_duration:
      days: 60
    passive_switch_opening_time:
      minutes: 4      
    initial_target_temp: 17.5
    custom_presets:
      night: 15
      holiday: 5    
    proportional_mode:
      control_interval:
        minutes: 15
      pwm_duration:
        minutes: 30
      pwm_scale: 100
      pwm_resolution: 50
      pwm_threshold: 2
      PID_mode:
        kp: 50
        ki: 0.004
        kd: -150000
        window_open_tempdrop: -3.6
      weather_mode:
        ka: 2
        kb: -20

  restore_from_old_state: True
  restore_parameters: True
  restore_integral: True


- platform: multizone_thermostat
  name: sl2
  unique_id: mz_sl2
  sensor: sensor.temp_sl2
  filter_mode: 2
  sensor_out: sensor.openweather_temperature
  room_area: 13
  initial_hvac_mode: "off"
  precision: 0.1
  sensor_stale_duration:
    hours: 12
  passive_switch_check: True
  heat:
    # thermostatic actuator
    entity_id: switch.verdeler_6
    passive_switch_duration:
      days: 60
    passive_switch_opening_time:
      minutes: 4  
    initial_target_temp: 17.5
    custom_presets:
      night: 15
      holiday: 5
    proportional_mode:
      control_interval:
        minutes: 15
      pwm_duration:
        minutes: 30
      pwm_scale: 100
      pwm_resolution: 50
      pwm_threshold: 2
      PID_mode:
        kp: 50
        ki: 0.004
        kd: -150000
        window_open_tempdrop: -3.6
      weather_mode:
        ka: 2
        kb: -20

  restore_from_old_state: True
  restore_parameters: True
  restore_integral: True

- platform: multizone_thermostat
  name: sl3
  unique_id: mz_sl3
  sensor: sensor.temp_sl3
  filter_mode: 2
  sensor_out: sensor.openweather_temperature
  room_area: 7
  initial_hvac_mode: "off"
  precision: 0.1
  sensor_stale_duration:
    hours: 12
  passive_switch_check: True
  heat:
    # thermostatic actuator
    entity_id: switch.verdeler_5
    passive_switch_duration:
      days: 60
    passive_switch_opening_time:
      minutes: 4  
    initial_target_temp: 17.5
    custom_presets:
      night: 15
      holiday: 5
    proportional_mode:
      control_interval:
        minutes: 15
      pwm_duration:
        minutes: 30
      pwm_scale: 100
      pwm_resolution: 50
      pwm_threshold: 2
      PID_mode:
        kp: 50
        ki: 0.004
        kd: -150000
        window_open_tempdrop: -3.6
      weather_mode:
        ka: 2
        kb: -20

  restore_from_old_state: True
  restore_parameters: True
  restore_integral: True


- platform: multizone_thermostat
  name: bathroom
  unique_id: mz_bathroom
  sensor: sensor.temp_bad
  filter_mode: 2
  room_area: 7
  initial_hvac_mode: "off"
  precision: 0.1
  sensor_stale_duration:
    hours: 12
  passive_switch_check: True
  heat:
    # thermostatic actuator
    entity_id: switch.verdeler_7
    passive_switch_duration:
      days: 60
    passive_switch_opening_time:
      minutes: 4  
    initial_target_temp: 19.0
    custom_presets:
      night: 15
      holiday: 5
    proportional_mode:
      control_interval:
        minutes: 15
      pwm_duration:
        minutes: 30
      pwm_scale: 100
      pwm_resolution: 50
      pwm_threshold: 2
      PID_mode:
        kp: 50
        ki: 0.004
        kd: -150000

  restore_from_old_state: True
  restore_parameters: True
  restore_integral: True

- platform: multizone_thermostat
  name: sl4
  unique_id: mz_sl4
  sensor: sensor.temp_sl4
  filter_mode: 2
  sensor_out: sensor.openweather_temperature
  room_area: 15
  initial_hvac_mode: "off"
  precision: 0.1
  sensor_stale_duration:
    hours: 12
  passive_switch_check: True
  heat:
    # radiator with eurotronic z-wave valve
    # proportional valve
    entity_id: number.sl4_valve_control
    passive_switch_duration:
      days: 60
    passive_switch_opening_time:
      minutes: 4  
    initial_target_temp: 17.5
    custom_presets:
      night: 15
      holiday: 5
    proportional_mode:
      control_interval:
        minutes: 15
      pwm_scale: 100
      pwm_resolution: 50
      pwm_threshold: 2
      PID_mode:
        kp: 10
        ki: 0.001
        kd: -100000
        window_open_tempdrop: -3.6
      weather_mode:
        ka: 2
        kb: -20

  restore_from_old_state: True
  restore_parameters: True
  restore_integral: True

- platform: multizone_thermostat
  name: sl5
  unique_id: mz_sl5
  sensor: sensor.temp_sl5
  filter_mode: 2
  sensor_out: sensor.openweather_temperature
  room_area: 18
  initial_hvac_mode: "off"
  precision: 0.1
  sensor_stale_duration:
    hours: 12
  passive_switch_check: True
  heat:
    # radiator with eurotronic z-wave valve
    # proportional valve  
    entity_id: number.sl5_valve_control
    passive_switch_duration:
      days: 60
    passive_switch_opening_time:
      minutes: 4  
    initial_target_temp: 17.5
    custom_presets:
      night: 15
      holiday: 5
    proportional_mode:
      control_interval:
        minutes: 15
      pwm_scale: 100
      pwm_resolution: 50
      pwm_threshold: 2
      PID_mode:
        kp: 10
        ki: 0.001
        kd: -100000
        window_open_tempdrop: -3.6
      weather_mode:
        ka: 2
        kb: -20

  restore_from_old_state: True
  restore_parameters: True
  restore_integral: True