input_boolean:
  fake_heater_input:
    name: Fake heater input
    initial: off
  fake_ac_input:
    name: Fake ac input
    initial: off

input_number:
  fake_sensor_temperature_1:
    initial: 20
    min: -20
    max: 35
    step: 0.01

sensor:
  - platform: template
    sensors:
      fake_sensor_1:
        unit_of_measurement: "degrees"
        value_template: "{{ states('input_number.fake_sensor_temperature_1') | float }}"
      temperature_therm:
        friendly_name: "temperature regelaar"
        value_template: "{{ state_attr('climate.on_off', 'current_temp_filt') | float}}"
        unit_of_measurement: "°C"

switch:
  - platform: template
    switches:
      fake_heater_switch:
        value_template: "{{ is_state('input_boolean.fake_heater_input', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.fake_heater_input
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.fake_heater_input
      fake_ac_switch:
        value_template: "{{ is_state('input_boolean.fake_ac_input', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.fake_ac_input
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.fake_ac_input

climate:
## on-off mode stand-alone - heat only - minimum definition
  - platform: multizone_thermostat
    name: simple_hysteric_heat_only
    unique_id: hysteric_heat_only
    sensor: sensor.fake_sensor_1
    heat:
      entity_id: switch.fake_heater_switch
      on_off_mode:
        hysteresis_on: 0.5
        hysteresis_off: 1

## on-off mode stand-alone - heat only - detailed example
  - platform: multizone_thermostat
    name: detailed_hysteric_heat_only
    unique_id: hysteric_heat_only
    sensor: sensor.fake_sensor_1
    filter_mode: 1
    sensor_stale_duration:
      hours: 4
    initial_hvac_mode: heat
    initial_preset_mode: away
    precision: 1
    heat:
      entity_id: switch.fake_heater_switch
      min_target_temp: 15
      max_target_temp: 25
      initial_target_temp: 19
      away_temp: 15
      on_off_mode:
        hysteresis_on: 0.5
        hysteresis_off: 1
        min_cycle_duration:
          minutes: 5
        control_interval:
          minutes: 3
    cool:
      entity_id: switch.fake_ac_switch
      min_target_temp: 15
      max_target_temp: 30
      initial_target_temp: 23
      away_temp: 28
      on_off_mode:
        hysteresis_on: 0.5
        hysteresis_off: 1
        min_cycle_duration:
          minutes: 5
        control_interval:
          minutes: 3

    restore_from_old_state: True
