input_number:
  fake_sensor_temperature_1:
    initial: 20
    min: -20
    max: 35
    step: 0.01
  fake_sensor_temperature_out:
    initial: 10
    min: -20
    max: 35
    step: 0.01

input_boolean:
  fake_heater_input:
    name: Fake heater input
    initial: off
  fake_ac_input:
    name: Fake ac input
    initial: off

sensor:
  - platform: template
    sensors:
      fake_sensor_1:
        unit_of_measurement: "degrees"
        value_template: "{{ states('input_number.fake_sensor_temperature_1') | float }}"
      fake_sensor_out:
        unit_of_measurement: "degrees"
        value_template: "{{ states('input_number.fake_sensor_temperature_out') | float }}"
      temperature_therm:
        friendly_name: "temperature regelaar"
        value_template: "{{ state_attr('climate.pid', 'current_temp_filt') | float}}"
        unit_of_measurement: "°C"

switch:
  - platform: template
    switches:
      fake_heater_switch:
        value_template: "{{ is_state('input_boolean.fake_heater_input', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.fake_heater_input
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.fake_heater_input
      fake_ac_switch:
        value_template: "{{ is_state('input_boolean.fake_ac_input', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.fake_ac_input
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.fake_ac_input

climate:
  # thermostat without outdoor temperature compensation
  - platform: multizone_thermostat
    name: pid_onoff_valve
    unique_id: mz_pid_onoff_valve
    sensor: sensor.fake_sensor_1
    filter_mode: 3
    initial_hvac_mode: "off"
    precision: 0.1
    sensor_stale_duration:
      hours: 3
    passive_switch_check: True
    heat:
      entity_id: switch.fake_heater_switch1
      passive_switch_duration:
        days: 15
      min_target_temp: 15
      max_target_temp: 24
      initial_target_temp: 21
      away_temp: 12        
      proportional_mode:
        control_interval:
          minutes: 5
        pwm_duration:
          minutes: 15
        pwm_scale: 100
        pwm_resolution: 20
        pwm_threshold: 5
        PID_mode:
          kp: 30
          ki: 0.003
          kd: -24000
          window_open_tempdrop: -3.6

    restore_from_old_state: True
    restore_parameters: True
    restore_integral: True

  # thermostat including outdoor temperature compensation
  - platform: multizone_thermostat
    name: pid_onoff_valve_weather
    unique_id: mz_pid_onoff_valve_weather
    sensor: sensor.fake_sensor_1
    filter_mode: 3
    sensor_out: sensor.fake_sensor_out
    initial_hvac_mode: "off"
    precision: 0.1
    sensor_stale_duration:
      hours: 3
    passive_switch_check: True
    heat:
      entity_id: switch.fake_heater_switch1
      passive_switch_duration:
        days: 15
      min_target_temp: 15
      max_target_temp: 24
      initial_target_temp: 21
      away_temp: 12        
      proportional_mode:
        control_interval:
          minutes: 5
        pwm_duration:
          minutes: 15
        pwm_scale: 100
        pwm_resolution: 20
        pwm_threshold: 5
        PID_mode:
          kp: 30
          ki: 0.003
          kd: -24000
          window_open_tempdrop: -3.6
        weather_mode:
          ka: 2
          kb: -10
          pwm_scale_low: -10
          pwm_scale_high: 50

    restore_from_old_state: True
    restore_parameters: True
    restore_integral: True
