input_boolean:
  fake_heater_input:
    name: Fake heater input
    initial: off
  fake_ac_input:
    name: Fake ac input
    initial: off

input_number:
  fake_sensor_outdoor_temperature_1:
    initial: 0
    min: -20
    max: 35
    step: 0.5

sensor:
  - platform: template
    sensors:
      fake_sensor_out:
        unit_of_measurement: "degrees"
        value_template: "{{ states('input_number.fake_sensor_outdoor_temperature_1') | float }}"
      temperature_therm:
        friendly_name: "temperature regelaar"
        value_template: "{{ state_attr('climate.weather', 'current_temp_filt') | float}}"
        unit_of_measurement: "°C"
switch:
  - platform: template
    switches:
      fake_heater_switch:
        value_template: "{{ is_state('input_boolean.fake_heater_input', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.fake_heater_input
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.fake_heater_input
      fake_ac_switch:
        value_template: "{{ is_state('input_boolean.fake_ac_input', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          entity_id: input_boolean.fake_ac_input
        turn_off:
          service: input_boolean.turn_off
          entity_id: input_boolean.fake_ac_input

climate:
  - platform: multizone_thermostat
    name: weather
    unique_id: mz_wc
    sensor_out: sensor.fake_sensor_out
    sensor_filter: 4
    initial_hvac_mode: "off"
    initial_preset_mode: "none"
    room_area: 60
    precision: 0.1
    sensor_stale_duration:
      hours: 3
    passive_switch_check: True
    heat:
      entity_id: switch.fake_heater_switch
      passive_switch_duration:
        hours: 5
      min_temp: 15
      max_temp: 24
      initial_target_temp: 21
      away_temp: 12
      proportional_mode:
        control_interval:
          seconds: 100
        difference: 100
        pwm:
          seconds: 120
        weather_mode:
          ka: 2
          kb: -6
    cool:
      entity_id: switch.fake_ac_switch
      passive_switch_duration:
        hours: 5
      min_temp: 15
      max_temp: 24
      initial_target_temp: 21
      away_temp: 12
      proportional_mode:
        control_interval:
          seconds: 100
        difference: 100
        pwm:
          seconds: 120
        weather_mode:
          ka: -2
          kb: 6

    restore_from_old_state: True
    restore_parameters: True
    restore_integral: False
