input_number:
  fake_sensor_temperature_1:
    initial: 20
    min: -20
    max: 35
    step: 0.01
  fake_pwm_heat:
    initial: 0
    min: 0
    max: 100
  fake_pwm_cool:
    initial: 0
    min: 0
    max: 100

sensor:
  - platform: template
    sensors:
      fake_sensor_1:
        unit_of_measurement: "degrees"
        value_template: "{{ states('input_number.fake_sensor_temperature_1') | float }}"
      temperature_therm:
        friendly_name: "temperature regelaar"
        value_template: "{{ state_attr('climate.pid', 'current_temp_filt') | float}}"
        unit_of_measurement: "°C"

climate:
  - platform: multizone_thermostat
    name: pid
    unique_id: mz_pid
    sensor: sensor.fake_sensor_1
    sensor_filter: 4
    initial_hvac_mode: "off"
    initial_preset_mode: "none"
    room_area: 60
    precision: 0.1
    sensor_stale_duration:
      hours: 3
    passive_switch_check: True
    heat:
      entity_id: input_number.fake_pwm_heat
      passive_switch_duration:
        hours: 5
      min_temp: 15
      max_temp: 24
      initial_target_temp: 21
      away_temp: 12
      proportional_mode:
        control_interval:
          seconds: 100
        difference: 100
        PID_mode:
          kp: 30
          ki: 0.003
          kd: -24000
          window_open_tempdrop: -3.6
    cool:
      entity_id: input_number.fake_pwm_cool
      passive_switch_duration:
        hours: 5
      min_temp: 15
      max_temp: 24
      initial_target_temp: 21
      away_temp: 12
      proportional_mode:
        control_interval:
          seconds: 100
        difference: 100
        PID_mode:
          kp: -30
          ki: -0.003
          kd: 24000
          window_open_tempdrop: 3.6

    restore_from_old_state: False
    restore_parameters: False
    restore_integral: False
